
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('products').del()
    .then(function () {
      // Inserts seed entries
      return knex('products').insert([

        // 0

        {id: 1, name: 'Kenmore High Efficiency Washer', price: 10, productImage: 'https://ebth-com-production.imgix.net/2017/11/01/14/54/07/20d007bc-8b8e-4e59-8441-219ce89ac491/IMG_0720.jpg?ixlib=rb-1.1.0&w=400&h=400&fit=crop&crop=&auto=format', description: 'This is a kenmore washer. It is clean and efficent.', _productOwner: 1, _category: 2 },
        {id: 2, name: 'Brooksfield 1bd room', price: 30, productImage: 'https://capi.myleasestar.com/v2/dimg-crop/54074308/400x400/54074308.jpg', description: 'One bedroom in my condo', _productOwner: 1, _category: 13 },
        {id: 3, name: 'BMX 2017 Fiend Embryo ', price: 1, productImage: 'https://i9x4h3t5.map2.ssl.hwcdn.net/products-new/1/mid_102750_Burgundy.jpg', description: 'great bike for your kids', _productOwner: 1, _category: 3 },
        {id: 4, name: 'Diamondback Syncr Pro', price: 2, productImage: 'https://www.sethsbikehacks.com/wp-content/uploads/2016/02/diamondback-syncr-pro-400x400.jpg', description: 'comfortable bike, for real bike riders.', _productOwner: 1, _category: 3 },
        {id: 5, name: 'Yoshimura Suzuki GSF/GSX1250', price: 30, productImage: 'https://cdn6.bigcommerce.com/s-coxd9/products/6180/images/393526/Yoshimura_R77_SlipOn_Suzuki_Bnadit1250_2011_detail__84919.1461787872.400.400.jpg?c=2', description: 'Get your drive on lol.', _productOwner: 1, _category: 14 },
        {id: 6, name: 'PlayStation 4', price: 2, productImage: 'https://www.techmart.lk/pub/media/catalog/product/cache/1/small_image/400x400/beff4985b56e3afdbeabfc89641a4582/p/l/playstation-4-techmart-gadget-store-colombo.png', description: 'PlayStation 4 500GB Console (PS4)', _productOwner: 1, _category: 11 },
        {id: 7, name: 'Canon T7i DSLR', price: 15, productImage: 'https://static.rcwilley.com/products/110707524/Canon-EOS-Rebel-T7i-DSLR-Camera-with-18-55mm-Lens-rcwilley-image1~400.jpg?r=9', description: 'Canon EOS Rebel T7i DSLR Camera with 18-55mm Lens', _productOwner: 1, _category: 6 },
        {id: 8, name: 'Canon 1D', price: 20, productImage: 'https://5.imimg.com/data5/CI/WD/MY-46128987/canon-eos-1d-x-body-dslr-camera-500x500.jpg', description: 'Canon EOS 1D X Body DSLR Camera', _productOwner: 1, _category: 6 },
        {id: 9, name: 'Yamaha JetSki', price: 25, productImage: 'https://static.wixstatic.com/media/595566_fff77feea75e4967b830d3611432b661.gif', description: 'blue and pink jetski', _productOwner: 1, _category: 16 },
        {id: 10, name: 'Apollo Tool Kit', price: 10, productImage: 'https://i.pinimg.com/originals/bf/9e/87/bf9e87001ef85ce20a4bdd9fb040ba7e.jpg', description: 'Apollo Precision Tools 95-Piece Mechanics Tool Kit', _productOwner: 1, _category: 7 },

        {id: 1, name: 'Wolf Stove', price: 15, productImage: 'https://www.drurydesigns.com/wp-content/uploads/2017/03/400-x-400-Not-So-Traditional-White-Kitchen-drury-design.jpg', description: 'Great stove. Stainless Steel design.', _productOwner: 2, _category: 2 },
        {id: 2, name: 'Regancy 3bd room', price: 65, productImage: 'https://capi.myleasestar.com/v2/dimg-crop/46083389/400x400/46083389.jpg', description: 'rent my whole apartment, when needed.', _productOwner: 2, _category: 13 },
        {id: 3, name: 'Spectrum Bike', price: 1, productImage: 'https://images.homedepot-static.com/productImages/c0bb3d3f-12df-4c32-907c-f0f027f73d18/svn/multi-huffy-bikes-23248-64_400_compressed.jpg', description: 'Spectre 20 in. Boys Metaloid Finish Bike', _productOwner: 2, _category: 3 },
        {id: 4, name: 'Two Brothers Suzuki B-King 08-09', price: 30, productImage: 'https://cdn6.bigcommerce.com/s-coxd9/products/47183/images/415208/Two_Brothers_BS_Suzuki_B-King_08-09__25878.1470414671.400.400.jpg?c=2', description: 'Got bikes', _productOwner: 2, _category: 14 },
        {id: 5, name: 'Xbox 360', price: 2, productImage: 'https://images.samsclubresources.com/is/image/samsclub/0088537013840_A?null', description: 'Get it while its available', _productOwner: 2, _category: 11 },
        {id: 6, name: 'Autozone 175pc Tool Set', price: 10, productImage: 'https://www.autozone.com/images/MEDIA_ProductCatalog/m4920015_08-duralast-tool-sets.png', description: 'Great for the majority of auto jobs.', _productOwner: 2, _category: 5 },
        {id: 7, name: '48 Laws of Power', price: 1, productImage: 'http://d310a9hpolx59w.cloudfront.net/product_photos/37687185/48_20Laws_20Of_20Power_400sq.jpeg', description: 'Good book by Robert Greene', _productOwner: 2, _category: 4 },
        {id: 8, name: 'Fengtu Mountaineering Bag ', price: 2, productImage: 'https://gloimg.gbtcdn.com/gb/pdm-provider-img/straight-product-img/20170901/T009677/T0096770001/goods-img/1504908549243515723.jpg', description: 'Fengtu 80L Outdoor Large Capacity Mountaineering Bag ', _productOwner: 2, _category: 15 },
        {id: 9, name: '2000 Buick Lesabre', price: 35, productImage: 'https://ebth-com-production.imgix.net/2016/05/20/07/38/45/734/DCS_4634.jpg?ixlib=rb-1.1.0&w=400&h=400&fit=crop&crop=&auto=format', description: 'Lightblue buick lasabre. Smells good , rides good.', _productOwner: 2, _category: 5 },
        {id: 10, name: 'Ipad Pro 10.5', price: 5, productImage: 'https://target.scene7.com/is/image/Target/52607161', description: 'Nice all white ipad', _productOwner: 2, _category: 8 },


        {id: 1, name: 'Paula Deen Tea Kettle', price: 1, productImage: 'https://imsdm.scene7.com/is/image/imsdm/745509_thumb_crop?$saMain$', description: 'This is a Paula Deen Garden Rooster Tea Kettle.', _productOwner: 3, _category: 2 },
        {id: 2, name: 'Folsom Bike', price: 2, productImage: 'https://folsombike.com/merchant/2538/images/template/hybrid-city-bikes.jpg', description: 'Nice hybrid bike, designed for long trips.', _productOwner: 3, _category: 3 },
        {id: 3, name: 'Yoshimura Kawasaki Ninja 650 12-16', price: 35, productImage: 'https://cdn6.bigcommerce.com/s-coxd9/products/6349/images/393345/Yoshimura_Kawasaki_Ninja_650_2012_Full_Exhaust_System_detail__30207.1461775440.400.400.jpg?c=2', description: 'mean green machine', _productOwner: 3, _category: 14 },
        {id: 4, name: 'Nintendo 64', price: 2, productImage: 'https://i.amz.mshcdn.com/yk4N4Zlyka0gjcikg5aTuAMLmCo=/http%3A%2F%2Fa.amz.mshcdn.com%2Fwp-content%2Fuploads%2F2015%2F01%2F16000798718_0e5ac370ef_o.jpg', description: 'Nintendo 64 with 007 game #IssaClassic', _productOwner: 3, _category: 11 },
        {id: 5, name: 'Bosch Drilling Tool', price: 2, productImage: 'https://images.homedepot-static.com/productImages/e4c600c2-e288-488b-90c9-0ec5779511b9/svn/bosch-rotary-drills-11255vsr-64_400_compressed.jpg', description: 'great tool for most jobs', _productOwner: 3, _category: 7 },
        {id: 6, name: 'Slims milwaukee m18 fuel 400', price: 4, productImage: 'http://www.slimspowertools.com/images/slims-milwaukee-m18-fuel-400.jpg', description: 'slims milwaukee m18 fuel 400', _productOwner: 3, _category: 7 },
        {id: 7, name: 'Rigid Staple Gun', price: 2, productImage: 'https://images.homedepot-static.com/productImages/937fea7e-0ed5-4bef-a981-f68322b2a40e/svn/ridgid-framing-nailers-r09892k-64_400_compressed.jpg', description: 'heavy duty staple gun', _productOwner: 3, _category: 7 },
        {id: 8, name: 'Scary Movie 4', price: 1, productImage: 'https://i.pinimg.com/736x/14/c5/9c/14c59c73d997619de17981e0c7a4d075--scary-movie--comedy-movies.jpg', description: 'oh so funny lol', _productOwner: 3, _category: 17 },
        {id: 9, name: 'The Assassins Blade', price: 1, productImage: 'https://i.pinimg.com/736x/d2/f5/f7/d2f5f79fecd09512fef5544c9793bf52--assassins-blade-martial-arts-movies.jpg', description: 'great movie', _productOwner: 3, _category: 17 },
        {id: 10, name: 'Indiania Jones and The Last Crusade', price: 1, productImage: 'https://i.pinimg.com/736x/ef/2e/ce/ef2ece95244368f6b5e6782fedb1a4b9--steven-spielberg--s.jpg', description: 'classic indiania jones movie', _productOwner: 3, _category: 17 },

        {id: 1, name: 'Professional 600 Series 6 Qt. Cobalt Blue Stand Mixer', price: 10, productImage: 'https://images.homedepot-static.com/productImages/fd591db3-f94b-4e75-b74d-6488efcb9990/svn/cobalt-blue-kitchenaid-stand-mixers-kp26m1xbu-64_400_compressed.jpg', description: 'Nice blue professional mixer.', _productOwner: 4, _category: 2 },
        {id: 2, name: 'Harley Davidson R443', price: 30, productImage: 'https://ocmotorcyclerental.com/wp-content/uploads/2017/02/Road-King3.jpg', description: 'For true Harley Davidson riders.', _productOwner: 4, _category: 14},
        {id: 3, name: 'Xbox One', price: 2, productImage: 'https://images-na.ssl-images-amazon.com/images/I/41-9v1OV%2B5L._QL40_SX400_.jpg', description: 'Because who doesnt love a xbox one.', _productOwner: 4, _category: 11 },
        {id: 4, name: 'The Hangover', price: 1, productImage: 'https://i.pinimg.com/736x/9a/3e/70/9a3e70bc01037bf0f6c5a860e5ee6fd2--bradley-cooper-so-funny.jpg', description: 'Enjoy the original hangover', _productOwner: 4, _category: 17 },
        {id: 5, name: 'Shrek Collection', price: 1, productImage: 'https://i.pinimg.com/736x/9a/3e/70/9a3e70bc01037bf0f6c5a860e5ee6fd2--bradley-cooper-so-funny.jpg', description: 'Enjoy this Shrek, 4 movie collection', _productOwner: 4, _category: 17 },
        {id: 6, name: 'Canon 6D', price: 65, productImage: 'https://i.ebayimg.com/00/s/MTAwMFgxMDAw/z/uhYAAOSwvD5Z6NRL/$_1.JPG', description: 'Canon 6D with cards, lens, tripod, ect', _productOwner: 4, _category: 2 },
        {id: 7, name: 'Magellan GPS', price: 2, productImage: 'https://i.pinimg.com/736x/21/61/33/2161339e339356f326f87ce0376b9d5f--car-accessories-gps-tracking.jpg', description: 'Magellan RoadMate 5220-LM 5-Inch GPS Navigator', _productOwner: 4, _category: 5 },
        {id: 8, name: '2016 Dogde Charger', price: 40, productImage: 'http://fasthemis.com/images/I23892819.jpg', description: 'Nice ride, to get around town.', _productOwner: 4, _category: 5 },
        {id: 9, name: '1bd room for rent', price: 55, productImage: 'https://www.onpropertyphuket.com/photos/tn_8516446049.jpg', description: 'renting my 1bd room in the hamptons', _productOwner: 4, _category: 13 },
        {id: 10, name: 'Felix Marti Clock', price: 45, productImage: 'https://ebth-com-production.imgix.net/2015/03/03/15/04/09/879/AMR_2409.jpg?ixlib=rb-1.1.0&w=400&h=400&fit=crop&crop=&auto=format', description: 'Felix Marti Figural Clock and Matching Lidded Jars', _productOwner: 4, _category: 1 },


        {id: 1, name: 'Caliber Pro Kamado Charcoal Grill-Stainless Steel-CTP22-SS', price: 10, productImage: 'http://www.bscculinary.com/media/catalog/product/cache/small_image/400x/9df78eab33525d08d6e5fb8d27136e95/c/t/ctp22-ss.jpg', description: 'great little staineless steel grill', _productOwner: 5, _category: 2 },
        {id: 2, name: 'Xbox One', price: 2, productImage: 'https://images-na.ssl-images-amazon.com/images/I/41-ZaZOH-3L._QL40_SX400_.jpg', description: 'Xbox One 500 GB Console', _productOwner: 5, _category: 11 },
        {id: 3, name: 'JT DL9 Paintball Marker', price: 10, productImage: 'https://www.discountpaintball.com/thumbnail.asp?file=assets/images/010-350-13729.jpg&maxx=400&maxy=400', description: 'nice paintball gun', _productOwner: 5, _category: 16 },
        {id: 4, name: 'Baden Basketball rack', price: 35, productImage: 'http://www.homerunsports.com/img/product/BA-RACK_1-B.jpg?fv=2F1E8BA7040F1D1F37251B3B6C727CDE-29273', description: 'Baden basketball rack with balls', _productOwner: 5, _category: 16 },
        {id: 5, name: 'Grizzly Basketball System', price: 35, productImage: 'http://www.biz2bizonline.com/sports/basketball/images/1291247.jpg', description: 'Good for playing basketball with your friends', _productOwner: 5, _category: 16},
        {id: 6, name: '14kt Herringbone Chain', price: 25, productImage: 'https://d1e0b1m7y2tal1.cloudfront.net/catalog/product/400x400/s/o/solid-yellow-gold-herringbone-chain-necklace-10k-4mm-wide_back.jpg', description: 'Want some bling bling!!!', _productOwner: 5, _category: 18 },
        {id: 7, name: '18kt Cuban Link Chain', price: 35, productImage: 'https://media.itshot.com/catalog/product/400x400/m/i/miami-yellow-gold-cuban-link-curb-chain-14k-8mm-22-40in_4.jpg', description: 'Get all the attention with this chain', _productOwner: 5, _category: 18 },
        {id: 8, name: '4 Hour Workweek', price: 1, productImage: 'https://img.thriftbooks.com/api/images/l/f49c2475e7adff30bbcf6632e52c64c66d3c236d.jpg', description: 'Read this masterpiece, by tim ferris', _productOwner: 5, _category: 4 },
        {id: 9, name: '4 Hour Body', price: 1, productImage: 'https://www.12minuteathlete.com/wp-content/uploads/2014/07/4-hour-body-400x400.jpg', description: 'great book about food and health', _productOwner: 5, _category: 4 },
        {id: 10, name: 'North Rim Sleeping Bag', price: 15, productImage: 'https://s7d1.scene7.com/is/image/Coleman/2000000104_Hero?wid=400&hei=400', description: 'North Rim™ Extreme Weather Sleeping Bag', _productOwner: 5, _category: 16 },


        {id: 1, name: 'Frigidaire Microwave', price: 5, productImage: 'http://www.orvilles.com/www/clients/orvillesappliance/product-images/436855_400X400.jpg', description: 'Microwave. Heats fast, and doesnt take up much space.', _productOwner: 6, _category: 2 },
        {id: 2, name: 'Dreamcast', price: 1, productImage: 'https://images-na.ssl-images-amazon.com/images/I/41E1mN8sIaL._QL40_SX400_.jpg', description: 'Classic dreamcast system. Everything was better in the past.', _productOwner: 6, _category: 11 },
        {id: 3, name: '2018 Marquis 720', price: 150, productImage: 'http://images0.boattrader.com/resize/1/56/72/4165672_20121211122258_1_LARGE.jpg?t=1252057', description: 'Nice yatch for you and your loved one.', _productOwner: 6, _category: 9 },
        {id: 4, name: 'Living Room Set', price: 15, productImage: 'http://adsshell.com/uploads/elegant-home-furniture-for-sale-in-brand-new-condition-even-u-can-gift-or-give-in-jahez-lahore_18217_1.jpg', description: 'Nice antique look', _productOwner: 6, _category: 19 },
        {id: 5, name: 'Jordan Living Room Set', price: 15, productImage: 'http://www.jordans.com/~/media/jordans%20redesign/category/furniture/living%20room/feature-livingroom.ashx?h=397&la=en&w=787&hash=459E0BF41F8262F530321C9DCD02EC818EEDA5E7', description: 'a living room set to fall in love with.', _productOwner: 6, _category: 19 },
        {id: 6, name: 'Sachtler Video Tripod', price: 30, productImage: 'http://www.kitmondo.com/remote.axd/kitmondo-images.s3.amazonaws.com/SiteImages/Images/Listing/e4b24b3e-bea9-4fdd-921e-395c1b84f70e.jpg?width=638&upscale=false', description: 'best tripod for your video needs', _productOwner: 6, _category: 6 },
        {id: 7, name: 'Canon Speedlite 600EX ', price: 15, productImage: 'https://www.ritzcamera.com/media/catalog/product/cache/1/small_image/400x/9df78eab33525d08d6e5fb8d27136e95/C/N/CN1177C002_15968.jpg', description: 'better light = better pictures.', _productOwner: 6, _category: 6 },
        {id: 8, name: '2017 Buick Lacrosse', price: 50, productImage: 'https://i2.wp.com/allthingsfadra.com/wp-content/uploads/2017/06/Buick-LaCrosse-old-school-house.jpg?resize=400%2C400', description: 'have sex appeal when you drive', _productOwner: 6, _category: 5 },
        {id: 9, name: 'MacBook Pro 13', price: 35, productImage: 'https://www.powermax.com/wp-content/uploads/2017/07/lrg-17-macbook-pro-13-silver-4-400x400.jpg', description: 'MacBook Pro 13 Silver i5 2.3GHz 8GB RAM 128GB Flash', _productOwner: 6, _category: 8 },
        {id: 10, name: 'Toshiba Satellite L50-B', price: 15, productImage: 'https://tesco.scene7.com/is/image/tesco/306-0470_PI_TPS2396644', description: 'nice little laptop', _productOwner: 6, _category: 8 },

        {id: 1, name: 'Russell Hobbs 100 Litre Chest Freezer', price: 5, productImage: 'https://www.tofs.com/media/catalog/product/cache/1/small_image/400x/9df78eab33525d08d6e5fb8d27136e95/5/9/592806_15.jpg', description: 'Eco-friendly chest freezer. Small but efficient.', _productOwner: 7, _category: 2 },
        {id: 2, name: 'Nintendo Game Console', price: 1, productImage: 'https://static.turbosquid.com/Preview/2014/05/23__23_45_36/Preview_c2.jpg9ab15455-2bbf-456d-8a84-293ea30bd576Larger.jpg', description: 'Take a trip to memory lane, with the classic nintendo system.', _productOwner: 7, _category: 2 },
        {id: 3, name: 'Call to Duty Black Ops 3', price: 1, productImage: 'http://images.shopko.com/get/w/400/h/400/2424_4001181_electronicsps4games.jpg?notfound=notavailable', description: 'Play some call to duty mannn', _productOwner: 7, _category: 2 },
        {id: 4, name: 'Crownline 564', price: 85, productImage: 'http://cdn.dealerspike.com/imglib/v1/800x600/imglib/trimsdb/5166131-0-20492021.jpg', description: 'fast boat, good time.', _productOwner: 7, _category: 9 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 7, _category: 2 },

        {id: 1, name: 'Candy GVSC Dryer ', price: 5, productImage: 'https://www.argos-support.co.uk/cache/large_square//images/7259775_R_Z001A.jpg', description: 'White Dryer. Gets the job done.', _productOwner: 8, _category: 2 },
        {id: 2, name: 'Crash Bandicoot Trilogy', price: 1, productImage: 'https://www.jbhifi.com.au/FileLibrary/ProductResources/Images/215169-L-LO.jpg', description: '3 games in one.', _productOwner: 8, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 8, _category: 2 },

        {id: 1, name: 'B60 Keurig Brewing System', price: 1, productImage: 'http://www.techfresh.net/wp-content/uploads/2012/09/keurig_b60_special_edition_brewer.jpg', description: 'Black coffee maker. Fast, easy.', _productOwner: 9, _category: 2 },
        {id: 2, name: 'Kirby Nightmare in Dream Land', price: 1, productImage: 'https://i.pinimg.com/736x/25/e5/37/25e537b3052f93890c8786a5c9be1e00--game-boy-advance-nintendo-games.jpg', description: 'Kirby game for gamebody advance', _productOwner: 9, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 9, _category: 2 },

        {id: 1, name: 'Wolf Toaster', price: 1, productImage: 'https://www.subzero-wolf.com/-/media/images/united-states/wg-images/product/wgtr104s-with-toast.jpg?width=400&height=400', description: 'My favorite toaster. Take care of her.', _productOwner: 10, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 10, _category: 2 },


        // 100

        {id: 1, name: 'Cuisinart Stick Hand', price: 1, productImage: 'http://www.bestappliancesreview.com/images/cuisinart-csb-76bc-smart-stick-hand-blender1.jpg', description: 'Nice little hand stick', _productOwner: 11, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 11, _category: 2 },

        {id: 1, name: 'Cordless Iron', price: 1, productImage: 'https://homestore365.com/Upload/Page_Images/cordless_steam_iron_daf9fdf0_s.jpg', description: 'Eco-friendly iron', _productOwner: 12, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 12, _category: 2 },

        {id: 1, name: 'Maytag Washer/Dryer', price: 3, productImage: 'http://www.amundsonsappliance.com/media/catalog/product/cache/thumbnail/400x/9df78eab33525d08d6e5fb8d27136e95/m/v/mvwc416fw12.png', description: '', _productOwner: 13, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 13, _category: 2 },

        {id: 1, name: 'Vitamix 5300', price: 2, productImage: 'https://images.samsclubresources.com/is/image/samsclub/0070311301372_A?null', description: 'polverizes vegatables and fruits.', _productOwner: 14, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 14, _category: 2 },

        {id: 1, name: 'DeLonghi ESAM3300 Espresso Machine', price: 2, productImage: 'https://coffeegeeklab.com/wp-content/uploads/2017/04/homepage3-e1495155500324.jpg', description: 'Awesome espresso machine', _productOwner: 15, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 15, _category: 2 },

        {id: 1, name: 'Keurig Z6000', price: 1, productImage: 'https://i5.walmartimages.com/asr/2f4e0dd7-9531-4066-8fcf-e3ce8596188b_1.f9ea057b359ffd21b94fbc0621c69c74.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF', description: 'Bolt Brewing System ', _productOwner: 16, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 16, _category: 2 },

        {id: 1, name: 'Remington Grooming Set', price: 1, productImage: 'https://i5.walmartimages.com/asr/f5cc08f8-8731-459a-9847-13cbe8035087_1.3b24faf4c07069d22adb7b84d6cded8b.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF', description: 'Remington Head-To-Toe Grooming Set, Mens Personal Electric Razor, Electric Shaver', _productOwner: 17, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 17, _category: 2 },

        {id: 1, name: 'Instant Pot IP-LUX60-ENW Pressure Cooker ', price: 2, productImage: 'https://walmart.ugc.bazaarvoice.com/1336/980935/photo.jpg', description: 'Stainless Steel 6-in-1 Pressure Cooker', _productOwner: 18, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 18, _category: 2 },

        {id: 1, name: 'Hamilton Beach Coffeemaker', price: 1, productImage: 'https://walmart.ugc.bazaarvoice.com/1336/159985/photo.jpg', description: 'Hamilton Beach Ensemble 12 Cup Coffeemaker', _productOwner: 19, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 19, _category: 2 },

        {id: 1, name: 'Danby DCR016C1BDB Compact Refrigerator ', price: 1, productImage: 'https://i5.walmartimages.com/asr/fb003f45-d18a-4446-a09c-3c5f31ed0096_1.cbc615c207872009e85bccf002e3150f.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF', description: 'Danby DCR016C1BDB 1.6 CF Compact Refrigerator ', _productOwner: 20, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 20, _category: 2 },


// 200

        {id: 1, name: 'Danby DAR044A6LDB Compact Refrigerator', price: 1, productImage: 'https://i5.walmartimages.com/asr/07b1f0be-0d38-429a-9200-14fc074aa609_1.ca9f428a6cf0220d3abd159d4308fa97.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF', description: 'Danby DAR044A6LDB 4.4 CF Compact Refrigerator', _productOwner: 21, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 21, _category: 2 },

        {id: 1, name: ' Avanti Mini kitchen with 2 burners', price: 1, productImage: '', description: ' Avanti Mini kitchen with 2 burners and Bake-Broil-Rotisserie-Convection functions, Black', _productOwner: 22, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 22, _category: 2 },

        {id: 1, name: 'Waring tf250 Turkey Fryer ', price: 1, productImage: 'https://www.bittopper.com/c/a9/f7/d0/bittopper_a9f7d04acccb0bbf5c06347f2224ae54-waring-pro-digital-rotisserie-turkey-fryer-tf250.jpg', description: 'waring pro digital rotisserie turkey fryer', _productOwner: 23, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 23, _category: 2 },

        {id: 1, name: 'T-fal VB2158 Beer-Tap System', price: 2, productImage: 'https://i5.walmartimages.com/asr/cc162dc8-a66f-4296-99c2-a7ecb4a18caa_1.ced8c41c5b72503339bb5a3835b56ac9.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF', description: 'Save money and make your own drafts. Great for house parties.', _productOwner: 24, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 24, _category: 2 },

        {id: 1, name: 'Magic Chef Mini Refrigerator', price: 2, productImage: 'https://i.pinimg.com/originals/1f/ab/ca/1fabca66fff09ef1f71003f3753b489d.jpg', description: '4.3 cu. ft. Mini Refrigerator in Stainless Look', _productOwner: 25, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 25, _category: 2 },

        {id: 1, name: 'Newalr Wine & Beverage Cooler', price: 2, productImage: 'https://www.homedepot.com/hdus/en_US/DTCCOMNEW/fetch/Category_Pages/Appliances/Freezers/wine-cooler.jpg', description: 'Wine & Beverage Cooler. Great for storing all your wines.', _productOwner: 26, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 26, _category: 2 },

        {id: 1, name: 'LG Kitchen Set', price: 5, productImage: 'https://images.samsclubresources.com/is/image/samsclub/0040619896379_A?null', description: 'Try out my stainless steel, kitchen set.', _productOwner: 27, _category: 2 },
        {id: 2, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 3, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 4, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 5, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 6, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 7, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 8, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 9, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },
        {id: 10, name: 'rowValue1', price: 0, productImage: '', description: '', _productOwner: 27, _category: 2 },

        // 270
 
      ]);
    });
};



const ProductsSchema = new mongoose.Schema({
  
      name: { type: String, required: true },
      price: { type: Number, required: true },
      productImage: {type: String, required: true },
      createdAt: { type: Date, default: Date.now },
      description: { type: String, required: true },
      isAvailable: { type: Boolean, default: false },
      _productOwner: { type: String, ref: 'Users' },
      _category: { type: Schema.ObjectId, ref: 'Categories' }
  
  });
  